

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'awstestaccount'
    regionName: 'ca-central-1'
    stackName: 'createdevopsstack'
    templateSource: 'file'
    templateFile: 'testcfn.yml'
